---
- name: Check Google Status
  hosts: localhost
  tasks:
    - name: Get HTTP status code from Google
      ansible.builtin.uri:
        url: https://www.google.com
        method: GET
        return_content: no
      register: http_response

    - name: Print the status code
      debug:
        msg: "HTTP Status Code: {{ http_response.status }}"
